name: Build and Deploy
on: 
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
          BRANCH: gh-pages
          ACCESS_TOKEN: ${{ secrets.DEPLOY }}
          BUILD_SCRIPT: pnpm install && pnpm run build
